### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [MaxShek/Skill7#1]
As we already mentioned, the link has to be within the end. You can [check your websites for HTML errors for free with the W3C Validator](http://validator.w3.org/check?uri=https%3A%2F%2Fmysterious-falls-8477.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Let me know when this has been fixed.

**Comment by MaxShek** [comment]
It has been fixed. Thank you.

**Comment by chrisvfritz** [comment]
:+1: Much better!
